name: Grading

on:
  pull_request:
    branches: [ main ]

jobs:
  test-basic:
    runs-on: ubuntu-latest
    outputs:
      supported_infix: ${{ steps.check_infix.outputs.supported }}
      supported_div: ${{ steps.check_div.outputs.supported }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 2
          token: ${{ secrets.GH_DB_TOKEN }}
      - name: Check repository clean
        run: ./5-grading-tests/scripts/check_clean.sh
      - name: Build
        run: ./5-grading-tests/scripts/build.sh
      - name: Test basic scenario
        run: ./5-grading-tests/scripts/test.sh
      - name: Check infix notation supported
        id: check_infix
        run: ./5-grading-tests/scripts/check_infix.sh >> "$GITHUB_OUTPUT"
      - name: Check division supported
        id: check_div
        run: ./5-grading-tests/scripts/check_div.sh >> "$GITHUB_OUTPUT"
  test-infix:
    runs-on: ubuntu-latest
    needs: test-basic
    if: needs.test-basic.outputs.supported_infix == 'yes'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 2
          token: ${{ secrets.GH_DB_TOKEN }}
      - name: Build
        run: ./5-grading-tests/scripts/build.sh
      - name: Test infix notation
        run: ./5-grading-tests/scripts/test_infix.sh
  test-div:
    runs-on: ubuntu-latest
    needs: test-basic
    if: needs.test-basic.outputs.supported_div == 'yes'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 2
          token: ${{ secrets.GH_DB_TOKEN }}
      - name: Build
        run: ./5-grading-tests/scripts/build.sh
      - name: Test division
        run: ./5-grading-tests/scripts/test_div.sh
